//  use Promise 

const asyncHandler = (requestHandler) => {
    (req, res, next) => {
        Promise.resolve(requestHandler(req, res, next)).catch((err) => next(err))
    }
}

export { asyncHandler }


// use try catch

// higher order function
// const asyncHandler = () => { }
// const asyncHandler = (fn) => () => {}
// const asyncHandler = (fn) => async () => {}
// higher order function

// const asyncHandler = (fn) => async (req, res, next) => {
//     try {
//         await fn(req, res, next)
//     } catch (error) {
//         res.status(error.code || 500).json({
//             success: false,
//             message: error.message
//         })
//     }
// }

// export { asyncHandler };